language: scala

scala:
 - 2.11.8
 
jdk:
 - oraclejdk8
 
branches:
 only:
  - master

cache:
  directories:
  - $HOME/.ivy2

notifications:
 email:
  recipients:
   - vlad@uralian.com
   
script:
 - sbt clean coverage test
 
after_success: 
 - sbt coveralls
